<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title><? loc PAGE_TITLE ?></title>
<link rel="stylesheet" type="text/css" href="/fixed/css/help/search.css" media="all" />
</head>
<body>

<div id="topbar">

    <table>
    <tr><td id="page_name"><? loc PAGE_NAME ?> </td>
    <td id="right_menu"><a href="/"><? loc NEW_SEARCH ?></a></td>
    </tr>
    </table>

</div>

<div id="main_area" align="center">

<div class="op_group_heading"><? loc BASE_OPERATORS_HEADING ?></div>
<div class="op_group_intro"><? loc BASE_OPERATORS_INTRO ?></div>

<div class="op_desc"><? loc ALL_SEARCH ?></div>
<div class="sample_header"><? loc ALL_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc ALL_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc ANY_SEARCH ?></div>
<div class="sample_header"><? loc ANY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc ANY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc URL_SEARCH ?></div>
<div class="sample_header"><? loc URL_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc URL_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc SITE_SEARCH ?></div>
<div class="sample_header"><? loc SITE_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc SITE_SEARCH_SAMPLES ?></div>

<div class="op_group_heading"><? loc LOGIC_OPERATORS_HEADING ?></div>
<div class="op_group_intro"><? loc LOGIC_OPERATORS_INTRO ?></div>

<div class="op_desc"><? loc AND_SEARCH ?></div>
<div class="sample_header"><? loc AND_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc AND_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc OR_SEARCH ?></div>
<div class="sample_header"><? loc OR_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc OR_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc EXCEPT_SEARCH ?></div>
<div class="sample_header"><? loc EXCEPT_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc EXCEPT_SEARCH_SAMPLES ?></div>
<div class="op_precedence"><? loc LOGIC_OPERATORS_PRECEDENCE ?></div>

<div class="op_group_heading"><? loc RESTRICTING_OPERATORS_HEADING ?></div>
<div class="op_group_intro"><? loc RESTRICTING_OPERATORS_INTRO ?></div>

<div class="op_desc"><? loc COUNTRY_SEARCH ?></div>
<div class="sample_header"><? loc COUNTRY_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc COUNTRY_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc LANG_SEARCH ?></div>
<div class="sample_header"><? loc LANG_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc LANG_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc DOMEN_SEARCH ?></div>
<div class="sample_header"><? loc DOMEN_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc DOMEN_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc FRESH_SEARCH ?></div>
<div class="sample_header"><? loc FRESH_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc FRESH_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc OUTDATED_SEARCH ?></div>
<div class="sample_header"><? loc OUTDATED_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc OUTDATED_SEARCH_SAMPLES ?></div>
<div class="op_desc"><? loc FEED_SEARCH ?></div>
<div class="sample_header"><? loc FEED_SEARCH_SAMPLE_HEADER ?></div>
<div class="samples"><? loc FEED_SEARCH_SAMPLES ?></div>
<div class="op_precedence"><? loc RESTRICTING_OPERATORS_PRECEDENCE ?></div>

<div class="op_group_heading"><? loc PROMPTING_HEADING ?></div>
<div class="op_group_intro"><? loc PROMPTING_DESC ?></div>

</div>

<div id="copyright" valign="bottom"><? loc COPYRIGHT ?> <a href="/static/<? lang ?>/contact"><? loc CONTACT ?></a></div>

<script>
  var browser="<? browser ?>";
  var os="<? os ?>";

  if(browser == "opera" || os != "windows")
  {
    var hot_key = document.getElementById("hk");

    if(hot_key != undefined)
    {
      hot_key.innerHTML = "Ctrl x";
    }
  }
</script>

</body>
</html>
