/*
 * product   : Elements - useful abstractions library.
 * copyright : Copyright (c) 2005-2016 Karen Arutyunov
 * licenses  : GNU GPL v2; see accompanying LICENSE file
 *             Commercial; contact karen.arutyunov@gmail.com
 */

/**
 * @file Elements/El/CORBA/Process/Control.idl
 * @author Karen Arutyunov
 * $id:$
 */

#ifndef _ELEMENTS_EL_CORBA_PROCESS_CONTROL_IDL_
#define _ELEMENTS_EL_CORBA_PROCESS_CONTROL_IDL_

module El
{
  module Corba
  {
    interface ProcessCtl
    {
      boolean status();
      void stop();
    };
  };  
};

#endif // _ELEMENTS_EL_CORBA_PROCESS_CONTROL_IDL_
